[package]
name = "blinky"
version = "0.1.0"
authors = ["Jérôme MEVEL <jeromeevel@hotmail.com>"]
edition = "2021"

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.0"
panic-halt = "0.2.0"
microbit-v2 = "0.12.0"
